#!/bin/bash
# ===========================================
# FloorEye Edge Agent Installer
# Usage: bash install.sh
# ===========================================
set -e

echo "============================================"
echo " FloorEye Edge Agent Installer"
echo "============================================"
echo ""

# Check prerequisites
if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker not installed. Install Docker first:"
    echo "  https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null && ! command -v docker-compose &>/dev/null; then
    echo "ERROR: Docker Compose not installed. Install Docker Compose first."
    exit 1
fi

echo "[OK] Docker found: $(docker --version)"

# Prompt for provisioning details
echo ""
echo "Enter the provisioning details from the FloorEye dashboard:"
echo "(Edge Agents > Provision Agent > copy the values)"
echo ""

read -p "Backend URL [https://app.puddlewatch.com]: " BACKEND_URL
BACKEND_URL=${BACKEND_URL:-https://app.puddlewatch.com}

read -p "Agent ID: " AGENT_ID
if [ -z "$AGENT_ID" ]; then echo "ERROR: Agent ID is required"; exit 1; fi

read -p "Edge Token: " EDGE_TOKEN
if [ -z "$EDGE_TOKEN" ]; then echo "ERROR: Edge Token is required"; exit 1; fi

read -p "Org ID: " ORG_ID
if [ -z "$ORG_ID" ]; then echo "ERROR: Org ID is required"; exit 1; fi

read -p "Store ID: " STORE_ID
if [ -z "$STORE_ID" ]; then echo "ERROR: Store ID is required"; exit 1; fi

read -p "Tunnel Token (optional, press Enter to skip): " TUNNEL_TOKEN

read -p "Edge API Key (from provisioning): " EDGE_API_KEY

# Installation directory
INSTALL_DIR="/opt/flooreye"
echo ""
echo "Installing to $INSTALL_DIR ..."

# Create directories
sudo mkdir -p "$INSTALL_DIR"/{data/{buffer,clips,frames,config,redis},models}
sudo chown -R "$(id -u):$(id -g)" "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Write .env
cat > .env <<EOF
# FloorEye Edge Agent Configuration
# Generated by install.sh on $(date -Iseconds)

# Identity (from provisioning)
BACKEND_URL=$BACKEND_URL
AGENT_ID=$AGENT_ID
EDGE_TOKEN=$EDGE_TOKEN
ORG_ID=$ORG_ID
STORE_ID=$STORE_ID
EDGE_API_KEY=$EDGE_API_KEY

# Cloudflare Tunnel (optional)
TUNNEL_TOKEN=$TUNNEL_TOKEN

# Ports (change if conflicts)
WEB_UI_PORT=8090
CONFIG_RECEIVER_PORT=8091

# Capture
CAPTURE_FPS=2
BATCH_INFERENCE=true
MAX_CONCURRENT_INFERENCES=4

# Storage
MAX_BUFFER_GB=2
FRAME_RETENTION_DAYS=30
CLIP_RETENTION_DAYS=90

# Logging
LOG_LEVEL=INFO
EOF
chmod 600 .env
echo "[OK] .env created"

# Copy docker-compose if not already present
if [ ! -f docker-compose.yml ]; then
    echo "NOTE: docker-compose.yml not found."
    echo "Copy docker-compose.yml from the FloorEye edge-agent directory."
    echo "Or use the docker-compose YAML from the provisioning response."
fi

# Pull and start
echo ""
echo "Starting FloorEye Edge Agent..."
if command -v docker-compose &>/dev/null; then
    docker-compose pull 2>/dev/null || true
    docker-compose up -d
else
    docker compose pull 2>/dev/null || true
    docker compose up -d
fi

echo ""
echo "============================================"
echo " FloorEye Edge Agent Started!"
echo "============================================"
echo ""
echo " Web UI:          http://localhost:8090"
echo " Config Receiver: http://localhost:8091"
echo " Install Dir:     $INSTALL_DIR"
echo ""
echo " Next steps:"
echo " 1. Open http://localhost:8090 to add cameras"
echo " 2. Or add cameras from the cloud dashboard"
echo " 3. Configure ROI + dry references on cloud dashboard"
echo ""
