"""
Edge Agent Service — provisioning, registration, heartbeat, commands, agent CRUD.
"""

import logging
import uuid
from datetime import datetime, timedelta, timezone

import httpx
import jwt
from fastapi import HTTPException, status
from motor.motor_asyncio import AsyncIOMotorDatabase

from app.core.config import settings
from app.core.org_filter import org_query
from app.core.security import hash_password
from app.services.system_log_service import emit_system_log

log = logging.getLogger("edge_service")


# ── Provisioning ────────────────────────────────────────────────


async def provision_agent(
    db: AsyncIOMotorDatabase,
    org_id: str,
    store_id: str,
    name: str,
) -> dict:
    """Generate edge agent token and create agent record."""
    # Verify store exists
    store = await db.stores.find_one({**org_query(org_id), "id": store_id, "is_active": True})
    if not store:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Store not found")

    agent_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    # Generate edge JWT
    payload = {
        "sub": agent_id,
        "org_id": org_id,
        "store_id": store_id,
        "type": "edge_agent",
        "iat": now,
        "exp": now + timedelta(days=settings.EDGE_TOKEN_EXPIRE_DAYS),
    }
    token = jwt.encode(payload, settings.EDGE_SECRET_KEY, algorithm="HS256")
    token_hash = hash_password(token)

    # Generate edge API key (for authenticating cloud→edge requests)
    import hashlib
    edge_api_key = hashlib.sha256(token.encode()).hexdigest()[:32]

    # Generate docker-compose template
    docker_compose = _generate_docker_compose(agent_id, store.get("name", name), org_id, store_id, edge_api_key)

    # Auto-create Cloudflare tunnel for edge-to-cloud connectivity
    tunnel_data = None
    if settings.CF_API_TOKEN and settings.CF_ACCOUNT_ID:
        try:
            from app.services.cloudflare_service import create_tunnel
            tunnel_data = await create_tunnel(agent_id, store.get("name", name))
        except Exception as e:
            log.warning("Cloudflare tunnel creation failed (non-critical): %s", e)

    agent_doc = {
        "id": agent_id,
        "org_id": org_id,
        "store_id": store_id,
        "name": name,
        "token_hash": token_hash,
        "edge_api_key": edge_api_key,
        "agent_version": None,
        "current_model_version": None,
        "status": "offline",
        "last_heartbeat": None,
        "cpu_percent": None,
        "ram_percent": None,
        "disk_percent": None,
        "gpu_percent": None,
        "inference_fps": None,
        "buffer_frames": 0,
        "buffer_size_mb": 0.0,
        "tunnel_status": None,
        "tunnel_latency_ms": None,
        "camera_count": 0,
        "cf_tunnel_id": tunnel_data["tunnel_id"] if tunnel_data else None,
        "cf_tunnel_token": tunnel_data["tunnel_token"] if tunnel_data else None,
        "cf_dns_record_id": tunnel_data["dns_record_id"] if tunnel_data else None,
        "tunnel_hostname": tunnel_data["hostname"] if tunnel_data else None,
        "created_at": now,
    }
    await db.edge_agents.insert_one(agent_doc)

    return {
        "agent_id": agent_id,
        "token": token,
        "docker_compose": docker_compose,
        "tunnel_token": tunnel_data["tunnel_token"] if tunnel_data else None,
        "tunnel_hostname": tunnel_data["hostname"] if tunnel_data else None,
    }


def _generate_docker_compose(agent_id: str, store_name: str,
                             org_id: str = "", store_id: str = "",
                             edge_api_key: str = "") -> str:
    """Generate a docker-compose.yml template for edge deployment.

    Includes all 4 services: inference-server, edge-agent, cloudflared, redis-buffer.
    GPU device mapping is included (Docker ignores if no GPU driver available).
    """
    backend_url = getattr(settings, "BACKEND_URL", "https://api.puddlewatch.com")
    return f"""# FloorEye Edge Agent — {store_name}
# Agent ID: {agent_id}
# Generated by FloorEye Cloud — do not edit manually
version: "3.8"

services:

  # ── Inference Server (ONNX Runtime) ──────────────────────────
  inference-server:
    image: flooreye/inference-server:latest
    container_name: flooreye-inference
    restart: unless-stopped
    volumes:
      - ./models:/models
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # ── Edge Agent (capture, validation, upload) ─────────────────
  edge-agent:
    image: flooreye/edge-agent:latest
    container_name: flooreye-edge-agent
    restart: unless-stopped
    env_file: .env
    environment:
      - AGENT_ID={agent_id}
      - ORG_ID={org_id}
      - STORE_ID={store_id}
      - BACKEND_URL={backend_url}
      - EDGE_TOKEN=${{EDGE_TOKEN}}
      - EDGE_API_KEY={edge_api_key}
      - TUNNEL_TOKEN=${{TUNNEL_TOKEN}}
    ports:
      - "${{WEB_UI_PORT:-8090}}:8090"
      - "${{CONFIG_RECEIVER_PORT:-8091}}:8091"
    volumes:
      - ./models:/models
      - ./data/buffer:/data/buffer
      - ./data/clips:/data/clips
      - ./data/frames:/data/frames
      - ./data/config:/data/config
      - ./data/redis:/data/redis
    depends_on:
      inference-server:
        condition: service_healthy
      redis-buffer:
        condition: service_started
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'

  # ── Cloudflare Tunnel (secure ingress) ───────────────────────
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: flooreye-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${{TUNNEL_TOKEN}}
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ── Redis Buffer (frame queue + offline buffer) ──────────────
  redis-buffer:
    image: redis:7-alpine
    container_name: flooreye-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory ${{MAX_BUFFER_GB:-2}}gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  flooreye-net:
    driver: bridge
"""


# ── Registration ────────────────────────────────────────────────


async def register_agent(
    db: AsyncIOMotorDatabase,
    agent_id: str,
    agent_version: str | None = None,
    camera_count: int = 0,
) -> dict:
    now = datetime.now(timezone.utc)
    updates = {
        "status": "online",
        "last_heartbeat": now,
    }
    if agent_version:
        updates["agent_version"] = agent_version
    if camera_count:
        updates["camera_count"] = camera_count

    result = await db.edge_agents.find_one_and_update(
        {"id": agent_id},
        {"$set": updates},
        return_document=True,
    )
    if not result:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    return result


# ── Heartbeat ───────────────────────────────────────────────────


async def process_heartbeat(
    db: AsyncIOMotorDatabase,
    agent_id: str,
    data: dict,
) -> dict:
    # Fetch previous status to detect offline→online transitions
    prev_agent = await db.edge_agents.find_one({"id": agent_id}, {"status": 1, "org_id": 1})
    prev_status = prev_agent.get("status") if prev_agent else None

    now = datetime.now(timezone.utc)
    updates = {
        "status": "online",
        "last_heartbeat": now,
        "cpu_percent": data.get("cpu_percent"),
        "ram_percent": data.get("ram_percent"),
        "disk_percent": data.get("disk_percent"),
        "gpu_percent": data.get("gpu_percent"),
        "inference_fps": data.get("inference_fps"),
        "buffer_frames": data.get("buffer_frames", 0),
        "buffer_size_mb": data.get("buffer_size_mb", 0.0),
        "tunnel_status": data.get("tunnel_status"),
        "tunnel_latency_ms": data.get("tunnel_latency_ms"),
        "camera_count": data.get("camera_count", 0),
    }
    # Store reachable URLs from heartbeat (for cloud→edge direct push)
    if data.get("tunnel_url"):
        updates["tunnel_url"] = data["tunnel_url"]
    if data.get("direct_url"):
        updates["direct_url"] = data["direct_url"]

    updates["device_count"] = data.get("device_count", 0)

    # ── Store new alert/diagnostic fields from edge heartbeat ──
    # Device status (per-device state, failures, triggers)
    device_status = data.get("device_status")
    if device_status is not None:
        updates["device_status"] = device_status

    # Model load status
    model_load_status = data.get("model_load_status")
    if model_load_status is not None:
        updates["model_load_status"] = model_load_status
    model_load_error = data.get("model_load_error")
    if model_load_error is not None:
        updates["model_load_error"] = model_load_error
    elif model_load_status == "ok":
        # Clear error when model is healthy
        updates["model_load_error"] = None

    # Inference server status
    inference_server_status = data.get("inference_server_status")
    if inference_server_status is not None:
        updates["inference_server_status"] = inference_server_status

    # Buffer dropped frames (cumulative)
    buffer_dropped = data.get("buffer_dropped_frames_total")
    if buffer_dropped is not None:
        updates["buffer_dropped_frames_total"] = buffer_dropped

    # Disk emergency active
    disk_emergency = data.get("disk_emergency_active")
    if disk_emergency is not None:
        updates["disk_emergency_active"] = disk_emergency

    # Validation settings synced
    validation_synced = data.get("validation_settings_synced")
    if validation_synced is not None:
        updates["validation_settings_synced"] = validation_synced

    # Enhanced cameras dict (includes last_inference_error, detection_blocked_reason)
    cameras_data = data.get("cameras")
    if cameras_data is not None:
        updates["cameras"] = cameras_data

    # Update device status from heartbeat
    devices_data = data.get("devices", {})
    if devices_data:
        for dev_name, dev_info in devices_data.items():
            cloud_id = dev_info.get("cloud_device_id")
            if cloud_id:
                await db.devices.update_one(
                    {"id": cloud_id},
                    {"$set": {"status": dev_info.get("status", "online"), "last_heartbeat": now}},
                )

    result = await db.edge_agents.find_one_and_update(
        {"id": agent_id},
        {"$set": updates},
        return_document=True,
    )
    if not result:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    org_id = result.get("org_id", "")

    # Emit system logs for critical resource thresholds
    disk_percent = data.get("disk_percent")
    if disk_percent is not None and disk_percent > settings.EDGE_AGENT_DISK_WARNING_PERCENT:
        await emit_system_log(
            db, org_id, "warning", "edge", "Edge agent disk usage critical",
            {"agent_id": agent_id, "disk_percent": disk_percent},
        )

    buffer_frames = data.get("buffer_frames", 0)
    # buffer_size_mb as percentage proxy: >80% of typical 2GB = 1600MB
    buffer_size_mb = data.get("buffer_size_mb", 0.0)
    if buffer_size_mb > settings.EDGE_AGENT_BUFFER_WARNING_MB:
        await emit_system_log(
            db, org_id, "warning", "edge", "Edge buffer near full",
            {"agent_id": agent_id, "buffer_size_mb": buffer_size_mb, "buffer_frames": buffer_frames},
        )

    # ── Emit system logs for new anomaly fields ──

    # Model load failure
    if model_load_status == "failed":
        await emit_system_log(
            db, org_id, "error", "edge", "Edge agent model load failed",
            {
                "agent_id": agent_id,
                "model_load_status": model_load_status,
                "model_load_error": model_load_error or "unknown",
            },
        )

    # Inference server unreachable
    if inference_server_status == "unreachable":
        await emit_system_log(
            db, org_id, "error", "edge", "Edge inference server unreachable",
            {"agent_id": agent_id, "inference_server_status": inference_server_status},
        )

    # Disk emergency
    if disk_emergency:
        await emit_system_log(
            db, org_id, "warning", "edge", "Edge agent disk emergency cleanup active",
            {"agent_id": agent_id, "disk_percent": disk_percent, "disk_emergency_active": True},
        )

    # Device failures — log if any device has >3 consecutive failures
    if device_status:
        for dev_name, dev_info in device_status.items():
            consec = dev_info.get("consecutive_failures", 0)
            if consec >= 3:
                await emit_system_log(
                    db, org_id, "warning", "edge",
                    f"Edge device '{dev_name}' has {consec} consecutive failures",
                    {
                        "agent_id": agent_id,
                        "device_name": dev_name,
                        "device_state": dev_info.get("state", "unknown"),
                        "consecutive_failures": consec,
                    },
                )

    return result


# ── Commands ────────────────────────────────────────────────────


async def send_command(
    db: AsyncIOMotorDatabase,
    agent_id: str,
    org_id: str,
    command_type: str,
    payload: dict,
    user_id: str,
    retry_count: int = 0,
) -> dict:
    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    now = datetime.now(timezone.utc)
    cmd = {
        "id": str(uuid.uuid4()),
        "agent_id": agent_id,
        "org_id": org_id,
        "command_type": command_type,
        "payload": payload,
        "status": "pending",
        "sent_by": user_id,
        "sent_at": now,
        "acked_at": None,
        "result": None,
        "error": None,
        "retry_count": retry_count,
    }
    await db.edge_commands.insert_one(cmd)
    cmd.pop("_id", None)
    return cmd


async def push_agent_update(
    db: AsyncIOMotorDatabase,
    agent_id: str,
    org_id: str,
    target_version: str,
    user_id: str,
) -> dict:
    """Send an update_agent command to an edge agent.

    The edge agent will pull the new Docker image and restart itself.
    The command is polled by the agent every 30 seconds.
    """
    return await send_command(db, agent_id, org_id, "update_agent", {
        "target_version": target_version,
    }, user_id)


async def get_pending_commands(
    db: AsyncIOMotorDatabase, agent_id: str
) -> list[dict]:
    cursor = db.edge_commands.find(
        {"agent_id": agent_id, "status": "pending"}
    ).sort("sent_at", 1)
    commands = await cursor.to_list(length=100)
    for cmd in commands:
        cmd.pop("_id", None)
    return commands


async def ack_command(
    db: AsyncIOMotorDatabase,
    command_id: str,
    ack_status: str,
    result: dict | None = None,
    error: str | None = None,
) -> dict:
    now = datetime.now(timezone.utc)
    updates = {
        "status": ack_status,
        "acked_at": now,
        "result": result,
        "error": error,
    }
    doc = await db.edge_commands.find_one_and_update(
        {"id": command_id},
        {"$set": updates},
        return_document=True,
    )
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Command not found")
    doc.pop("_id", None)

    # Update model version on successful deploy_model ACK
    if ack_status in ("completed", "success") and doc.get("command_type") == "deploy_model":
        model_version_id = doc.get("payload", {}).get("model_version_id")
        if model_version_id:
            await db.edge_agents.update_one(
                {"id": doc["agent_id"]},
                {"$set": {"current_model_version": model_version_id, "updated_at": now}},
            )

    # On failure, retry up to 3 times or mark camera as sync_failed
    if ack_status == "failure":
        cmd = await db.edge_commands.find_one({"id": command_id})
        if cmd:
            retry_count = cmd.get("retry_count", 0)
            if retry_count < 3:
                # Re-queue with incremented retry
                await send_command(
                    db, cmd["agent_id"], cmd.get("org_id", ""),
                    command_type=cmd["command_type"],
                    payload=cmd["payload"],
                    user_id=cmd.get("sent_by", "system"),
                    retry_count=retry_count + 1,
                )
                log.info("Re-queued command %s (retry %d/3)", command_id, retry_count + 1)
            else:
                # Max retries — mark camera as sync_failed
                camera_id = cmd.get("payload", {}).get("camera_id")
                if camera_id:
                    await db.cameras.update_one(
                        {"id": camera_id},
                        {"$set": {"config_status": "sync_failed", "config_ack_error": error or "max retries exceeded"}}
                    )
                    log.warning("Config sync failed for camera %s after 3 retries", camera_id)

    return doc


# ── Class & Model Push ──────────────────────────────────────────


async def push_classes_to_edge(
    db: AsyncIOMotorDatabase,
    org_id: str,
    agent_id: str | None = None,
    user_id: str = "system",
) -> list[dict]:
    """Push current class definitions to edge agent(s) via edge commands.

    If agent_id is specified, push to that agent only; otherwise push to all
    agents belonging to the org.

    Returns list of created command documents.
    """
    # Try detection_classes first (model-sourced), fall back to class_definitions
    det_classes = await db.detection_classes.find(
        {"org_id": org_id} if org_id else {}
    ).to_list(length=100)

    if det_classes:
        # Include ALL per-class override fields for edge autonomy
        classes_payload = [
            {
                "id": str(c.get("class_id", i)),
                "name": c.get("name", ""),
                "enabled": c.get("enabled", True),
                "alert_on_detect": c.get("alert_on_detect", True),
                "min_confidence": c.get("min_confidence", 0.5),
                "min_area_percent": c.get("min_area_percent", 0.0),
                "incident_enabled": c.get("incident_enabled", True),
                "incident_severity_override": c.get("incident_severity_override"),
                "incident_grouping_separate": c.get("incident_grouping_separate", False),
                "device_trigger_enabled": c.get("device_trigger_enabled", True),
            }
            for i, c in enumerate(det_classes)
        ]
    else:
        class_def = await db.class_definitions.find_one({"org_id": org_id})
        if not class_def:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No classes found. Load a model or sync classes first.",
            )
        classes_payload = class_def.get("classes", [])

    # Determine target agents
    if agent_id:
        agents = [await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})]
        if not agents[0]:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    else:
        agents = await db.edge_agents.find(org_query(org_id)).to_list(length=1000)

    commands = []
    for agent in agents:
        cmd = await send_command(
            db,
            agent["id"],
            org_id,
            command_type="update_classes",
            payload={"classes": classes_payload, "synced_at": datetime.now(timezone.utc).isoformat()},
            user_id=user_id,
        )
        commands.append(cmd)

    return commands


async def push_model_to_edge(
    db: AsyncIOMotorDatabase,
    org_id: str,
    agent_id: str,
    model_version_id: str,
    user_id: str = "system",
) -> dict:
    """Push a model version to an edge agent via edge command.

    The edge agent will download the model, verify the checksum, and hot-swap.
    """
    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    model = await db.model_versions.find_one({"id": model_version_id, "org_id": org_id})
    if not model:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Model version not found")

    if model.get("model_source") == "yolo_cloud":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cloud-only models cannot be deployed to edge agents",
        )

    # Generate presigned download URL from S3 key
    onnx_key = model.get("onnx_path") or ""
    if not onnx_key:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Model version has no downloadable artifact (onnx_path not set)",
        )

    from app.services.storage_service import generate_url
    download_url = await generate_url(onnx_key, expires=7200)

    cmd = await send_command(
        db,
        agent_id,
        org_id,
        command_type="deploy_model",
        payload={
            "model_version_id": model["id"],
            "version_id": model["id"],
            "version_str": model.get("version_str", ""),
            "download_url": download_url,
            "checksum": model.get("checksum", ""),
            "format": "onnx",
            "model_source": model.get("model_source", "local_onnx"),
        },
        user_id=user_id,
    )

    # Model version is updated when the edge agent ACKs the deploy_model command
    # (see ack_command()) — NOT optimistically here before actual deployment

    return cmd


async def _try_direct_push(
    agent: dict,
    command_type: str,
    payload: dict,
) -> bool:
    """Attempt direct HTTP push to edge agent via tunnel_url then direct_url.

    Tries tunnel_url:8091 first, falls back to direct_url:8091.
    Returns True if the push succeeded on either URL, False otherwise.
    """
    edge_api_key = agent.get("edge_api_key", "")
    headers = {"X-Edge-Api-Key": edge_api_key, "Content-Type": "application/json"}
    body = {"command_type": command_type, "payload": payload}

    urls_to_try: list[tuple[str, str]] = []
    tunnel_url = agent.get("tunnel_url")
    direct_url = agent.get("direct_url")

    if tunnel_url:
        # Strip trailing slash, append port + endpoint
        base = tunnel_url.rstrip("/")
        # Tunnel URLs (e.g. Cloudflare) typically proxy to the port already,
        # so try with port first, then without
        urls_to_try.append(("tunnel", f"{base}:8091/api/push"))
        urls_to_try.append(("tunnel_no_port", f"{base}/api/push"))
    if direct_url:
        base = direct_url.rstrip("/")
        urls_to_try.append(("direct", f"{base}:8091/api/push"))

    async with httpx.AsyncClient() as client:
        for label, url in urls_to_try:
            try:
                resp = await client.post(url, json=body, headers=headers, timeout=settings.HTTP_TIMEOUT_FAST)
                if resp.status_code < 300:
                    log.info("Direct push succeeded via %s → %s", label, url)
                    return True
                log.debug("Direct push to %s returned %d", url, resp.status_code)
            except Exception as exc:
                log.debug("Direct push to %s failed: %s", url, exc)

    return False


async def push_agent_config(
    db: AsyncIOMotorDatabase,
    org_id: str,
    agent_id: str,
    config: dict,
    user_id: str = "system",
) -> dict:
    """Push configuration update to edge agent.

    Fallback chain:
    1. Try direct HTTP push via tunnel_url:8091
    2. Try direct HTTP push via direct_url:8091
    3. If both fail, queue as a pending command for the agent to poll

    Validates config fields before pushing.
    """
    allowed_fields = {
        "detection_fps",
        "confidence_threshold",
        "upload_interval_seconds",
        "max_uploads_per_minute",
        "model_version_id",
        "resolution_width",
        "resolution_height",
        "enable_preview",
        "log_level",
        "heartbeat_interval_seconds",
        "offline_buffer_size",
        "roi_zones",
    }

    unknown = set(config.keys()) - allowed_fields
    if unknown:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Unknown config fields: {', '.join(sorted(unknown))}",
        )

    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    # Attempt direct push first (tunnel_url → direct_url)
    pushed_directly = await _try_direct_push(agent, "push_config", config)

    if pushed_directly:
        # Create command record marked as already delivered
        now = datetime.now(timezone.utc)
        cmd = {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "org_id": org_id,
            "command_type": "push_config",
            "payload": config,
            "status": "delivered",
            "sent_by": user_id,
            "sent_at": now,
            "acked_at": now,
            "result": {"delivery": "direct_push"},
            "error": None,
        }
        await db.edge_commands.insert_one(cmd)
        cmd.pop("_id", None)
    else:
        # Fallback: queue as pending command for agent to poll
        log.info("Direct push failed for agent %s — queuing command", agent_id)
        cmd = await send_command(
            db,
            agent_id,
            org_id,
            command_type="push_config",
            payload=config,
            user_id=user_id,
        )

    # Also persist config on the agent document
    now = datetime.now(timezone.utc)
    await db.edge_agents.update_one(
        {"id": agent_id},
        {"$set": {"config": config, "config_updated_at": now, "updated_at": now}},
    )

    return cmd


# ── Agent CRUD ──────────────────────────────────────────────────


async def list_agents(
    db: AsyncIOMotorDatabase,
    org_id: str,
    store_id: str | None = None,
    limit: int = 20,
    offset: int = 0,
) -> tuple[list[dict], int]:
    query: dict = org_query(org_id)
    if store_id:
        query["store_id"] = store_id

    total = await db.edge_agents.count_documents(query)
    cursor = db.edge_agents.find(query).sort("created_at", -1).skip(offset).limit(limit)
    agents = await cursor.to_list(length=limit)
    return agents, total


async def get_agent(db: AsyncIOMotorDatabase, agent_id: str, org_id: str) -> dict:
    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    return agent


async def delete_agent(db: AsyncIOMotorDatabase, agent_id: str, org_id: str) -> None:
    # Fetch agent before deletion for tunnel cleanup
    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    # Clean up Cloudflare tunnel if one was auto-created
    if agent.get("cf_tunnel_id") and settings.CF_API_TOKEN:
        try:
            from app.services.cloudflare_service import delete_tunnel
            await delete_tunnel(agent["cf_tunnel_id"], agent.get("cf_dns_record_id"))
        except Exception as e:
            log.warning("Cloudflare tunnel cleanup failed: %s", e)

    await db.edge_agents.delete_one({"id": agent_id, "org_id": org_id})
    await db.edge_commands.delete_many({"agent_id": agent_id})
    # Unlink cameras — don't delete them, just clear the agent reference
    await db.cameras.update_many(
        {"edge_agent_id": agent_id, "org_id": org_id},
        {"$set": {"edge_agent_id": None, "config_status": "unlinked"}},
    )


async def update_agent(
    db: AsyncIOMotorDatabase, agent_id: str, org_id: str, name: str | None = None
) -> dict:
    """Update edge agent properties."""
    agent = await db.edge_agents.find_one({**org_query(org_id), "id": agent_id})
    if not agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    updates = {}
    if name is not None:
        updates["name"] = name
    if updates:
        updates["updated_at"] = datetime.now(timezone.utc)
        await db.edge_agents.update_one({"id": agent_id}, {"$set": updates})
        agent.update(updates)
    agent.pop("_id", None)
    return agent


async def mark_stale_agents_offline(
    db: AsyncIOMotorDatabase,
    stale_threshold_minutes: int | None = None,
) -> int:
    """Mark agents as offline if their last heartbeat exceeds the threshold.

    Returns the number of agents marked offline. Emits a system log for each.
    Called periodically by the health worker.
    """
    if stale_threshold_minutes is None:
        stale_threshold_minutes = settings.EDGE_AGENT_STALE_THRESHOLD_MINUTES
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=stale_threshold_minutes)
    query = {
        "status": "online",
        "last_heartbeat": {"$lt": cutoff},
    }
    stale_agents = await db.edge_agents.find(query).to_list(length=1000)
    count = 0
    for agent in stale_agents:
        await db.edge_agents.update_one(
            {"id": agent["id"]},
            {"$set": {"status": "offline"}},
        )
        org_id = agent.get("org_id", "")
        await emit_system_log(
            db, org_id, "error", "edge", "Edge agent offline",
            {"agent_id": agent["id"], "last_heartbeat": agent.get("last_heartbeat", "").isoformat() if hasattr(agent.get("last_heartbeat", ""), "isoformat") else str(agent.get("last_heartbeat", ""))},
        )
        count += 1
    return count


async def check_config_staleness(db: AsyncIOMotorDatabase, agent_id: str, camera_configs: dict) -> list:
    """Compare edge-reported config versions against cloud versions.
    Returns list of cameras that need config updates.
    """
    if not camera_configs:
        return []

    camera_ids = list(camera_configs.keys())
    cameras = await db.cameras.find(
        {"id": {"$in": camera_ids}, "edge_agent_id": agent_id},
        {"id": 1, "config_version": 1, "_id": 0}
    ).to_list(500)

    stale = []
    for cam in cameras:
        cloud_ver = cam.get("config_version", 0)
        edge_info = camera_configs.get(cam["id"], {})
        edge_ver = edge_info.get("config_version", 0) if isinstance(edge_info, dict) else 0
        if cloud_ver > edge_ver:
            stale.append({
                "camera_id": cam["id"],
                "cloud_version": cloud_ver,
                "edge_version": edge_ver,
            })
    return stale
