"""Edge Setup Bundle Service — generates a downloadable ZIP for edge device setup."""

import io
import logging
import os
import zipfile
from pathlib import Path

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.core.config import settings
from app.utils.s3_utils import download_from_s3

log = logging.getLogger("edge_bundle_service")

# Path to edge-agent source code (relative to backend/)
_EDGE_AGENT_ROOT = Path(__file__).resolve().parent.parent.parent.parent / "edge-agent"


def _generate_env(agent: dict, token: str, tunnel_token: str | None = None) -> str:
    """Generate .env file with all required variables pre-filled."""
    lines = [
        f"EDGE_TOKEN={token}",
        f"AGENT_ID={agent['id']}",
        f"ORG_ID={agent['org_id']}",
        f"STORE_ID={agent['store_id']}",
        f"BACKEND_URL={settings.BACKEND_URL}",
        f"EDGE_API_KEY={agent.get('edge_api_key', '')}",
    ]
    if tunnel_token:
        lines.append(f"TUNNEL_TOKEN={tunnel_token}")
    else:
        lines.append("# TUNNEL_TOKEN=  # Optional: add Cloudflare tunnel token for remote management")
    return "\n".join(lines) + "\n"


def _generate_compose(has_tunnel: bool = True) -> str:
    """Generate docker-compose.yml based on the real edge-agent compose.

    Uses build: directives (source included in bundle) with correct healthchecks,
    logging, and all 5 services from the production compose.
    """
    tunnel_section = ""
    if has_tunnel:
        tunnel_section = """
  # ── Cloudflare Tunnel (secure cloud-to-edge connectivity) ─────
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: flooreye-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - flooreye-net
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
"""

    return f"""# FloorEye Edge Agent
# Generated by FloorEye Cloud — run: bash install.sh
version: "3.8"

services:

  # ── Inference Server (ONNX Runtime) ──────────────────────────
  inference-server:
    build:
      context: .
      dockerfile: Dockerfile.inference
    container_name: flooreye-inference
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    volumes:
      - ./models:/models
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ── Edge Agent (capture, validation, upload) ─────────────────
  edge-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: flooreye-edge-agent
    restart: unless-stopped
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    ports:
      - "${{WEB_UI_PORT:-8090}}:8090"
      - "${{CONFIG_RECEIVER_PORT:-8091}}:8091"
    volumes:
      - ./models:/models
      - ./data/buffer:/data/buffer
      - ./data/clips:/data/clips
      - ./data/frames:/data/frames
      - ./data/config:/data/config
      - ./data/redis:/data/redis
    depends_on:
      inference-server:
        condition: service_healthy
      redis-buffer:
        condition: service_started
    networks:
      - flooreye-net
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8091/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'

  # ── go2rtc (RTSP re-streaming for live view) ────────────────
  go2rtc:
    image: alexxit/go2rtc
    container_name: flooreye-go2rtc
    restart: unless-stopped
    ports:
      - "${{GO2RTC_PORT:-1984}}:1984"
    volumes:
      - ./data/config/go2rtc.yaml:/config/go2rtc.yaml
    networks:
      - flooreye-net
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:1984/api"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: ${{GO2RTC_MEMORY_LIMIT:-512M}}
          cpus: '1'
{tunnel_section}
  # ── Redis Buffer (frame queue + offline buffer) ──────────────
  redis-buffer:
    image: redis:7-alpine
    container_name: flooreye-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory ${{MAX_BUFFER_GB:-2}}gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - flooreye-net
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  flooreye-net:
    driver: bridge
"""


def _generate_gpu_override() -> str:
    """Generate docker-compose.gpu.yml for GPU-enabled inference."""
    return """# GPU override — used automatically by install.sh when NVIDIA GPU is detected
services:
  inference-server:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
"""


def _generate_install_script() -> str:
    """Generate install.sh — the one-command installer."""
    return """#!/bin/bash
set -e
echo "=== FloorEye Edge Agent Setup ==="
echo ""

# Create required directories
mkdir -p models data/buffer data/clips data/frames data/config data/redis
echo "✓ Directories created"

# Create default go2rtc config if missing
if [ ! -f data/config/go2rtc.yaml ]; then
    echo "streams: {}" > data/config/go2rtc.yaml
    echo "✓ go2rtc config created"
fi

# Check for model
if [ -f models/model.onnx ]; then
    echo "✓ AI model found"
elif ls models/*.onnx 1>/dev/null 2>&1; then
    echo "✓ AI model found"
else
    echo "⚠ No AI model found — agent will download from cloud on first boot"
fi

# Detect GPU
if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
    echo "✓ NVIDIA GPU detected — using GPU inference"
    COMPOSE_CMD="docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d --build"
else
    echo "• No GPU detected — using CPU inference (slower but works)"
    COMPOSE_CMD="docker compose up -d --build"
fi

# Start containers
echo ""
echo "Building and starting containers (this may take a few minutes on first run)..."
$COMPOSE_CMD

# Wait for health
echo ""
echo "Waiting for agent to start..."
for i in $(seq 1 90); do
    if curl -sf http://localhost:8091/api/health >/dev/null 2>&1; then
        echo ""
        echo "============================================"
        echo "  ✓ FloorEye Edge Agent is ONLINE"
        echo "============================================"
        echo ""
        echo "  Web UI:    http://localhost:8090"
        echo "  Health:    http://localhost:8091/api/health"
        echo ""
        echo "  Next: Go to your cloud dashboard and add cameras."
        echo ""
        exit 0
    fi
    sleep 2
    printf "."
done
echo ""
echo "⚠ Agent did not start within 3 minutes."
echo "  Check logs: docker compose logs -f"
echo "  Common issues:"
echo "    - Docker not running: sudo systemctl start docker"
echo "    - Port conflict: check if 8080/8090/8091 are in use"
exit 1
"""


def _generate_readme(agent: dict, hostname: str | None = None) -> str:
    """Generate README.txt with setup instructions."""
    tunnel_line = f"  Tunnel:    https://{hostname}" if hostname else "  Tunnel:    Not configured (optional)"
    return f"""FloorEye Edge Agent Setup
========================

Agent:    {agent['name']}
Agent ID: {agent['id']}
Store ID: {agent['store_id']}
{tunnel_line}

Quick Start:
  1. bash install.sh
  2. Wait for "Edge Agent is ONLINE" message
  3. Go to your cloud dashboard to add cameras

Commands:
  Start:    docker compose up -d
  Stop:     docker compose down
  Logs:     docker compose logs -f
  Restart:  docker compose restart
  Update:   docker compose pull && docker compose up -d --build

Files:
  .env                    — credentials (do not share)
  docker-compose.yml      — container configuration
  docker-compose.gpu.yml  — GPU override (auto-detected)
  models/                 — AI model files
  data/                   — detection data, clips, config
"""


async def generate_setup_bundle(
    db: AsyncIOMotorDatabase,
    agent: dict,
    token: str,
    tunnel_token: str | None = None,
) -> bytes:
    """Generate a complete edge setup bundle as a ZIP file.

    Includes: docker-compose, .env, install.sh, source code, and optionally the production ONNX model.
    """
    has_tunnel = bool(tunnel_token)
    hostname = agent.get("tunnel_hostname")

    # Generate config files
    env_content = _generate_env(agent, token, tunnel_token)
    compose_content = _generate_compose(has_tunnel)
    gpu_override = _generate_gpu_override()
    install_script = _generate_install_script()
    readme = _generate_readme(agent, hostname)

    # Try to include the production ONNX model
    onnx_bytes = None
    try:
        model = await db.model_versions.find_one(
            {"org_id": agent["org_id"], "status": "production"},
            sort=[("promoted_to_production_at", -1)],
        )
        if model and model.get("onnx_path"):
            onnx_bytes = await download_from_s3(model["onnx_path"])
            log.info("Including production model in bundle: %s (%.1f MB)",
                     model.get("version_str", "unknown"),
                     len(onnx_bytes) / 1024 / 1024)
    except Exception as e:
        log.warning("Could not include model in bundle: %s", e)

    # Build ZIP in memory
    prefix = "flooreye-edge"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Config files
        zf.writestr(f"{prefix}/docker-compose.yml", compose_content)
        zf.writestr(f"{prefix}/docker-compose.gpu.yml", gpu_override)
        zf.writestr(f"{prefix}/.env", env_content)
        zf.writestr(f"{prefix}/install.sh", install_script)
        zf.writestr(f"{prefix}/README.txt", readme)

        # Default go2rtc config
        zf.writestr(f"{prefix}/data/config/go2rtc.yaml", "streams: {}\n")

        # ONNX model (if available)
        if onnx_bytes:
            zf.writestr(f"{prefix}/models/model.onnx", onnx_bytes)

        # Edge agent source code (for docker build)
        _add_source_files(zf, prefix)

    return buf.getvalue()


def _add_source_files(zf: zipfile.ZipFile, prefix: str) -> None:
    """Add edge-agent source files to the ZIP for local Docker builds."""
    if not _EDGE_AGENT_ROOT.exists():
        log.warning("Edge agent source not found at %s — bundle will use image: references", _EDGE_AGENT_ROOT)
        return

    # Files and directories to include
    include_patterns = [
        "Dockerfile.agent",
        "Dockerfile.inference",
        "requirements.txt",
        "requirements-inference.txt",
        "agent/",
        "inference-server/",
        "web/",
    ]

    for pattern in include_patterns:
        src = _EDGE_AGENT_ROOT / pattern
        if src.is_file():
            zf.write(str(src), f"{prefix}/{pattern}")
        elif src.is_dir():
            for root, _dirs, files in os.walk(str(src)):
                # Skip __pycache__ and .pyc files
                _dirs[:] = [d for d in _dirs if d != "__pycache__"]
                for fname in files:
                    if fname.endswith(".pyc"):
                        continue
                    full = os.path.join(root, fname)
                    rel = os.path.relpath(full, str(_EDGE_AGENT_ROOT))
                    zf.write(full, f"{prefix}/{rel}")
