"""
Storage Service — S3/MinIO/R2 file operations with local filesystem fallback.

Provides upload, download, delete, and presigned URL generation.
"""

import logging

from app.core.config import settings
from app.utils.s3_utils import (
    _s3_configured,
    get_s3_client,
    upload_to_s3,
    download_from_s3,
    delete_from_s3,
)

log = logging.getLogger(__name__)


async def upload_file(
    key: str,
    data: bytes,
    content_type: str = "image/jpeg",
) -> str:
    """
    Upload file to configured storage backend.

    Returns the URL or path where the file was stored.
    """
    return await upload_to_s3(key, data, content_type)


async def download_file(key: str) -> bytes:
    """Download file from configured storage backend."""
    return await download_from_s3(key)


async def delete_file(key: str) -> bool:
    """Delete file from configured storage backend."""
    return await delete_from_s3(key)


def _get_public_s3_url() -> str:
    """Get the browser-accessible S3/MinIO URL.

    Priority:
    1. S3_PUBLIC_URL env var (explicit override for production)
    2. Replace Docker internal hostname with localhost (dev fallback)
    """
    if settings.S3_PUBLIC_URL:
        return settings.S3_PUBLIC_URL

    # Auto-detect: replace Docker internal hostnames with localhost
    internal = settings.S3_ENDPOINT_URL
    import re
    # Replace common Docker internal hostnames: minio, s3, storage, etc.
    public = re.sub(r"http://[a-zA-Z0-9_-]+:(\d+)", r"http://localhost:\1", internal)
    return public


def _rewrite_url_for_browser(url: str) -> str:
    """Rewrite a presigned URL to use the public S3 endpoint.

    Presigned URLs are signed against the internal endpoint hostname.
    For MinIO, the signature is host-independent, so we can safely
    rewrite the hostname portion without invalidating the signature.
    """
    internal = settings.S3_ENDPOINT_URL
    public = _get_public_s3_url()
    if internal != public and internal in url:
        return url.replace(internal, public, 1)
    return url


_public_s3_client = None
_public_s3_client_url = None


def _get_public_s3_client():
    """Get an S3 client configured with the PUBLIC endpoint URL.

    Presigned URLs generated by this client will be signed for the public
    hostname (e.g., localhost:9000) so browsers can access them without
    host mismatch signature errors.
    """
    global _public_s3_client, _public_s3_client_url
    public_url = _get_public_s3_url()
    if _public_s3_client is not None and _public_s3_client_url == public_url:
        return _public_s3_client
    try:
        import boto3
        from botocore.config import Config
        _public_s3_client = boto3.client(
            "s3",
            endpoint_url=public_url,
            aws_access_key_id=settings.S3_ACCESS_KEY_ID,
            aws_secret_access_key=settings.S3_SECRET_ACCESS_KEY,
            region_name=settings.S3_REGION,
            config=Config(signature_version="s3v4"),
        )
        _public_s3_client_url = public_url
        return _public_s3_client
    except Exception:
        return None


async def generate_url(key: str, expires: int = 3600) -> str:
    """
    Generate a browser-accessible presigned URL for the given storage key.

    Uses a separate S3 client configured with the PUBLIC endpoint URL so
    the presigned signature matches the browser's request host.

    Args:
        key: The storage key / object path.
        expires: URL expiry in seconds (default 3600 = 1 hour).

    Returns:
        A presigned URL string accessible from the browser.
    """
    if _s3_configured():
        # Use public-endpoint client for browser-accessible presigned URLs
        client = _get_public_s3_client() or get_s3_client()
        if client:
            try:
                url = client.generate_presigned_url(
                    "get_object",
                    Params={
                        "Bucket": settings.S3_BUCKET_NAME,
                        "Key": key,
                    },
                    ExpiresIn=expires,
                )
                return url
            except Exception as exc:
                log.error("Presigned URL generation failed: %s", exc)

    # Fallback: return direct URL or local path
    if _s3_configured():
        public = _get_public_s3_url()
        return f"{public}/{settings.S3_BUCKET_NAME}/{key}"

    from pathlib import Path
    local_path = Path(settings.LOCAL_STORAGE_PATH) / key
    return str(local_path)
